### ISSUE TITLE
creating and editing of Projects

### ISSUE THREAD

**Issue by LevantBoris** [marinus-g/TodoList-Backend#8]
Als registrierter Benutzer möchte ich Projekte erstellen und bearbeiten können, damit ich meine Aufgaben passend organisieren kann.

Akzeptanzkriterien:

- Speichern und Anzeige des neuen Projekts in der Projektliste mit Titel und Beschreibung
- Projekt kann erzeugt, aufgerufen, bearbeitet oder gelöscht werden.

**Comment by Bockkwurst** [comment]
- Formular erstellen ist ein eigenes FE Ticket
- Projekte Filtern ist ein eigenes FE Ticket
- Übersicht TODO ist ein eigenes FE Ticket
- CRUD TODO ist ein eigenes BE Ticket
- ToDos zuweisen ist ein eigenes BE und FE Ticket (seperat)
